### ISSUE TITLE
Move JsonGen.swift to separate library

### ISSUE THREAD

**Issue by tomlokhorst** [tomlokhorst/swift-json-gen#12]
~~Instead of having to copy JsonGen.swift manually, generate the file.~~

All standard encoders and decoders in JsonGen.swift should be in a library (available through CocoaPods).
The ISO 8601 NSDate decoder can be in a separate subspec, so users can supply their own NSDate decoder if they need a different formatting.

**Comment by fraserscottmorrison** [comment]
You could create a CocoaPod for JsonGen.swift

**Comment by tomlokhorst** [comment]
Yes, that's a good idea.

I've been thinking I want to give users the ability to write encoders/decoders for specific types that currently are in `JsonGen.swift`. But I can't really come up with a reason why you'd want to do so.

Except for the [NSDate implementation](https://github.com/tomlokhorst/swift-json-gen/blob/develop/example/JsonGen.swift#L160), because that one is really specific to my use case.

So maybe I should just write a special case for NSDate and put everything else in library.

**Comment by tomlokhorst** [comment]
I'm working on the [Statham](https://github.com/tomlokhorst/Statham/) library.

JsonGen probably needs to be told the (Pods) directory, so that the equivalent of the current `JsonGen.swift` can be passed to swiftc. Because source files refer to typealiases like `AnyJson` and `JsonObject`

It should be something like: `swift-json-gen --statham-directory=Pods/Statham/Sources some_input/directory`

**Comment by tomlokhorst** [comment]
Released in 0.6.0
