### ISSUE TITLE
Encoding usage

### ISSUE THREAD

**Issue by ghost** [tomlokhorst/swift-json-gen#13]
I'm just getting into the serialization topic, and the code generation with your tool is working pretty well. However, your "getting started" explanation just covers the decoding of a JSON item into a Swift struct. So, I'm struggling with the encoding of a Swift struct to a JSON item. How to do this? 

Thanks a lot in advance for your support!

Best regards
Hardy

**Comment by tomlokhorst** [comment]
Hi Hardy, thanks for using JsonGen!

It's a good idea to update the "getting started" documentation, I'll put that on my todo list.

For now, here's an example of how to decode and encode some JSON:

```
let inputStr = "{ \"title\": \"Hello, World!\", \"published\": true, \"author\": { \"first\": \"Tom\", \"last\": \"Lokhorst\" } }"
let inputData = inputStr.dataUsingEncoding(NSUTF8StringEncoding)!

let inputObj = try! NSJSONSerialization.JSONObjectWithData(inputData, options: [])

let test = Blog.decodeJson(inputObj)!

let outputObj = test.encodeJson()
let outputData = try! NSJSONSerialization.dataWithJSONObject(outputObj, options: NSJSONWritingOptions.PrettyPrinted)
let outputStr = String(data: outputData, encoding: NSUTF8StringEncoding)!
```

**Comment by ghost** [comment]
Great, thanks a lot! This helps me on!
