### ISSUE TITLE
Howto change XCode reference?

### ISSUE THREAD

**Issue by ghost** [tomlokhorst/swift-json-gen#14]
Just another question: I updated XCode from Beta to GM, now I can't execute swift-json-gen anymore. The error is: 

xcrun: error: can't exec '/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc' (errno=No such file or directory)

I already uninstalled/installed node, npm, swift-json-gen, but no change. How can I reset the XCode app link?

**Comment by tomlokhorst** [comment]
I accidentally released a wrong version. Sorry about that.

If you update to version 0.2.1 from NPM, everything should work.

**Comment by ghost** [comment]
hm… still no change:

perth:~ ladmin$ npm install swift-json-gen
swift-json-gen@0.2.1 node_modules/swift-json-gen
perth:~ ladmin$ 

perth:~ ladmin$ swift-json-gen
USAGE: swift-json-gen some/directory/FileWithStructs.swift
  Generates +JsonGen.swift files for all swift files supplied,
  filenames ending with +Extensions.swift are excluded.

xcrun: error: can't exec '/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc' (errno=No such file or directory)

**Comment by tomlokhorst** [comment]
I think you're using two separate versions of `swift-json-gen`.

You're installing the new one in `node_modules/swift-json-gen` in the local directory, and there's the old one installed somewhere globally.

Check with `swift-json-gen --version` that you're actually using the 0.2.1 version.
To install globally, run `sudo npm install -g swift-json-gen`

**Comment by ghost** [comment]
Aaaah, now it works. Thanks a lot for your fast support!
