### ISSUE TITLE
Howto inject UIKit?

### ISSUE THREAD

**Issue by ghost** [tomlokhorst/swift-json-gen#15]
I have a struct that owns an init() using UIKit functions (for convenience reasons). However, the struct properties are base types only. When compiling with swift-json-gen, there is an "error: no such module 'UIKit'".

How can it make UIKit known to swift-json-gen?

**Comment by tomlokhorst** [comment]
The easiest way of dealing with external modules is by putting all code that isn’t directly related to the JSON in a separate file.  

All files with names ending in `+Extensions.swift` are ignored by JsonGen.
So you can put a struct extension in that file with UIKit specific code.

**Comment by ghost** [comment]
Ah, great, will try this.
