### ISSUE TITLE
Make Swift-JSON-gen available on something like brew or pod

### ISSUE THREAD

**Issue by mac-cain13** [tomlokhorst/swift-json-gen#17]
So it doesn't need to be a submodule in every project using it.

**Comment by tomlokhorst** [comment]
JsonGen is available as an NPM package.

I recommend creating a `generate_json_decoders.sh` script in you repo:

```
echo "Installing version-locked swift-json-gen"
npm install --dev swift-json-gen@0.2.2

echo "Generating JSON decoders..."
node node_modules/swift-json-gen/bin/swift-json-gen AwesomeApp/Json/

echo "Done!"
```

Also, it may be wise to add `node_modules/` to your `.gitignore` file.

**Comment by mac-cain13** [comment]
Quite nice solution! :+1:
