### ISSUE TITLE
Support nested structs/enums in extensions

### ISSUE THREAD

**Issue by tomlokhorst** [tomlokhorst/swift-json-gen#22]
Something like:

``` swift
struct One {
  let title: String
  let two: One.Two
}

extension One {
  struct Two {
    let title: String
  }
}
```

Requested by @timvansteenis

**Comment by tomlokhorst** [comment]
Looking into this, I'm not sure what code JsonGen should generate.

This doesn't seem to be allowed:

``` swift
extension One.Two {
}
```

@timvansteenis Any ideas?

**Comment by timvansteenis** [comment]
Hmm, i'm pretty sure this was about supporting nesting multiple levels of structs. eg:

```
struct One {
  struct Two {
    struct Three {
    }
  }
}
```

JsonGen didn't generate valid encoders / decoders for the 3rd+ layer.

**Comment by tomlokhorst** [comment]
Ok, probably a related to https://github.com/tomlokhorst/swift-json-gen/issues/9 then.

Your particular example works in 0.4.0
