### ISSUE TITLE
Support for classes

### ISSUE THREAD

**Issue by fraserscottmorrison** [tomlokhorst/swift-json-gen#25]
Another suggestion :) 

I want to use classes rather than structs for most of my models. It'd be good if your tool would support classes (shouldn't be too hard). Currently I just change by class to a struct temporarily then execute your tool and change back to a class ;)

**Comment by tomlokhorst** [comment]
Classes aren't supported for several reasons:
1. In contrast to structs, the compiler doesn't automatically generate an initialiser for classes.
2. They're complicated with difficult inheritance rules and overrides and so on.
3. Reference semantics are complicated and difficult to use compared to the value semantics of structs. See also Apple's WWDC talk: [Building Better Apps with Value Types in Swift](https://developer.apple.com/videos/play/wwdc2015-414/)

For these reasons I don't think it's a good idea to build in support for classes in JsonGen.
Although as a user you can still write your own decoders, and those will work fine together with generated decoders.

I feel classes just add a lot of complexity to JsonGen with very little benefit.
