### ISSUE TITLE
Return error info instead of just nil

### ISSUE THREAD

**Issue by mac-cain13** [tomlokhorst/swift-json-gen#3]
Would be nice to have some more detailed info about why things failed. @sdevos suggested to use some kind of Result enum containing either the Json object or the NSError, I think that's a nice suggestion.

**Comment by tomlokhorst** [comment]
Also, fix the error message.

https://github.com/tomlokhorst/swift-json-gen/blob/develop/lib/SwiftPrinter.ts#L242

Is missing "a" or "an" in the text.

**Comment by tomlokhorst** [comment]
@mac-cain13 What would you prefer for Swift 2?

`static func decodeJson(json: AnyObject) -> JsonDecodeResult<MyStruct>`
or:
`static func decodeJson(json: AnyObject) throws -> MyStruct`

If we create a enum with specific errors (FieldMissing, WrongType) we could throw those.

I guess this also depends on if we throw on the first error, or collect all errors together.
A list of multiple errors is a lot harder to catch match on, but perhaps that's not a requirement?

**Comment by mac-cain13** [comment]
Throwing looks like the way to go. More Swift 2 like and does the job as good.

**Comment by tomlokhorst** [comment]
I agree, throwing is the correct way here.
The current optional behaviour can be recreated by simply calling decodeJson with `try?`.

The currently generated assertFailures can then be removed, and the user of the decodeJson function can write that themselves in the `catch` block.

**Comment by tomlokhorst** [comment]
Continued discussion in: https://github.com/tomlokhorst/swift-json-gen/pull/21
