### ISSUE TITLE
Add option to pass output folder

### ISSUE THREAD

**Issue by mac-cain13** [tomlokhorst/swift-json-gen#30]
It would be nice to be able to pass the output folder to JsonGen so we can control where files end up.

Possible argument syntax could be:
`swift-json-gen /input/folderA /output/folderA /input/folderB /output/folderB`
or 
`swift-json-gen /input/folderA /input/folderB --output-folder /output/folder`

**Comment by tomlokhorst** [comment]
Available in release 0.5.0
