### ISSUE TITLE
Escape swift keywords in generated code.

### ISSUE THREAD

**Issue by sdevos** [tomlokhorst/swift-json-gen#34]
json-gen produces invalid code if you try to generate decoders for objects with Swift keywords as member names. In swift you can escape keywords with `back ticks`, json-gen should do the same.

e.g.

``` swift
struct Foo {
  let `break`: Bool
}
```

**Comment by tomlokhorst** [comment]
Duplicate of https://github.com/tomlokhorst/swift-json-gen/issues/33
