### ISSUE TITLE
Generated decoder breaks when using generics in Swift 3.1

### ISSUE THREAD

**Issue by mbernson** [tomlokhorst/swift-json-gen#39]
I am using JSONGen in a project to generate a decoder for this struct:

```swift
public struct Response<T> {
  let seq: Int
  public let status: Status
  public let content: T
}
```

Using Swift 3.0, this generated a decode function which takes a function that decodes `T`:

`static func decodeJson(_ decodeT: @escaping (Any) throws -> T) -> (Any) throws -> Response`

In Swift 3.1 however, the decoder doesn't do this and tries to call `T.decodeJson`, which doesn't work:

`static func decodeJson(_ json: Any) throws -> Response {
    let decoder = try JsonDecoder(json: json) `

I suspect this is because Apple changed something in swiftc version 3.1, but I have yet to figure out exactly what. For now, I can keep using the old generated decoder which compiles just fine.

**Comment by tomlokhorst** [comment]
Uh oh... that seems like a bug in JsonGen. I'll have a look at it.

Did you at least get a warning about the `swiftc` version?

**Comment by mbernson** [comment]
Yes, it did warn me about using an untested swifc version.

**Comment by tomlokhorst** [comment]
Swift 3.1 support has been added in version 1.2.

Thanks for reporting this issue!
